server:
  port: 8001 # 前端只访问这个端口

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 地址
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 60s
      # 开启从注册中心动态发现服务
      discovery:
        locator:
          enabled: true
      # 路由配置
      routes:
        - id: problem
          uri: lb://problem # lb 代表负载均衡，后面跟 Nacos 中的服务名
          predicates:
            - Path=/problems/**, /api/admin/problems/**

        - id: judge
          uri: lb://judge
          predicates:
            - Path=/judge/**

        - id: submission
          uri: lb://submission
          predicates:
            - Path=/submissions/**

        - id: competition
          uri: lb://competition # 对应比赛服务的 application.name
          predicates:
            - Path=/competitions/**, /api/admin/competitions/**, /api/admin/problems/**

        - id: user
          uri: lb://user # 使用负载均衡指向 Nacos 注册的服务
          predicates:
            - Path=/api/**

      # 全局跨域配置 (让前端 5173 能够访问网关)
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" # 允许所有来源（生产环境建议指定具体域名）
            allowedMethods: "*"
            allowedHeaders: "*"