server:
  port: 8085 # 比赛服务的端口

spring:
  application:
    name: competition
  datasource:
    # 替换为你的数据库名
    url: jdbc:mysql://localhost:3306/sit_oj?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 13575877459hhh # 替换为你的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开发环境打印SQL
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.competition.entity

# Feign 超时配置 (关键：判题是长连接)
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 60000 # 设置为 60 秒，防止判题时出现 Read timed out
      submission-service: # 针对判题服务可以单独设置
        readTimeout: 30000

# JWT 配置
jwt:
  # 必须至少 32 个字符，确保 HS256 算法安全
  secret: SIT_ALGORITHM_COMMUNITY_SECRET_KEY_2026_SECURE_VERSION
  # 过期时间，单位：毫秒 (86400000 = 24小时)
  expiration: 86400000