server:
  port: 8081

spring:
  application:
    name: problem
  datasource:
    url: jdbc:mysql://localhost:3306/sit_oj?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 13575877459hhh
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB       # 单个文件最大限制
      max-request-size: 50MB    # 单次请求总数据大小限制

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 你的 Nacos 地址

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 在控制台打印 SQL 语句，方便调试

oj:
  testcase:
    # 远程服务器配置
    remote-host: 123.60.72.80
    remote-path: /root/ojdemo/OnlineJudgeDeploy/data/backend/test_case
    remote-user: root
    remote-password: 13575877459hhH
    # 本地存储配置
    local-base-path: ../data/test_case
    enable-remote-sync: false  # 开发环境下设为 true，部署到服务器设为 false

jwt:
  # 必须至少 32 个字符，确保 HS256 算法安全
  secret: SIT_ALGORITHM_COMMUNITY_SECRET_KEY_2026_SECURE_VERSION
  # 过期时间，单位：毫秒 (86400000 = 24小时)
  expiration: 86400000