server:
  port: 8084


spring:
  application:
    name: user # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    # 替换为你的数据库名
    url: jdbc:mysql://localhost:3306/sit_oj?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 13575877459hhh # 替换为你的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: 924849252@qq.com
    password: qkmwqaagfbckbcia # 注意：这里是授权码，不是登录密码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启 SQL 日志方便调试
    map-underscore-to-camel-case: true  # 必须为 true
  mapper-locations: classpath*:/mapper/**/*.xml


# JWT 配置
jwt:
  # 必须至少 32 个字符，确保 HS256 算法安全
  secret: SIT_ALGORITHM_COMMUNITY_SECRET_KEY_2026_SECURE_VERSION
  # 过期时间，单位：毫秒 (86400000 = 24小时)
  expiration: 86400000