server {
    listen       80;
    server_name  localhost;

    # A. 静态资源（前端页面）
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html; # 这一行保证了单页面应用路由正常
    }

    # B. 后端接口“白名单”转发
    # 只要是请求这些路径开头的，全部转发给网关
    location ~* ^/(api|problems|submissions|competitions|judge)/ {
        proxy_pass http://oj-gateway:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}